# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Resume.create(user_id: 1)
# Introduction.create(name: "Zakwan", title: "Full Stack Developer", address: "New York, NY", phone: "9293239120",email: "zakwanbhaiyat23@gmail.com",resume_id: 1)
# Summary.create(description: "I'm a design-minded Full Stack web developer focused on building beautiful interfaces & experiences. I pride myself on my ability to consistently expand my coding skills and stay on top of current design trends. I'm looking to enhance my technical skills as a programmer and web developer in a collaborative environment.",resume_id: 1)
# Objective.create(description: "I'm a design-minded Full Stack web developer focused on building beautiful interfaces & experiences. I pride myself on my ability to consistently expand my coding skills and stay on top of current design trends. I'm looking to enhance my technical skills as a programmer and web developer in a collaborative environment.",resume_id: 1)
# Skill.create(name:  "Rails", resume_id: 1)
Skill.create(name:  "RAILS")
Skill.create(name:  "RUBY")
Skill.create(name:  "SINATRA")
Skill.create(name:  "JQUERY")
Skill.create(name:  "JAVASCRIPT")
Skill.create(name:  "CSS")
Skill.create(name:  "HTML")
Skill.create(name:  "GITHUB")
Skill.create(name:  "SUBLIME TEXT")
Skill.create(name:  "JAVA")
Skill.create(name:  "R")
Skill.create(name:  "PHP")
Skill.create(name:  "SASS")
Skill.create(name:  "PROJECT MANAGMENT")
Skill.create(name:  "PHOTOSHOP")
Skill.create(name:  "Data Analysis")
Skill.create(name:  "Copywriting")
Skill.create(name:  "Foreign Languages")
Skill.create(name:  "Accounting")
Skill.create(name:  "Computer Languages")
Skill.create(name:  "Mathematics")
Skill.create(name:  "Graphic Design")
Skill.create(name:  "Planning / Event Planning")
Skill.create(name:  "SEO / SEM Marketing")
Skill.create(name:  "Bookkeeping")
Skill.create(name:  "Communication")
Skill.create(name:  "Ability to Work Under Pressure")
Skill.create(name:  "Decision Making")
Skill.create(name:  "Time Management")
Skill.create(name:  "Self-motivation")
Skill.create(name:  "Conflict Resolution")
Skill.create(name:  "Leadership")
Skill.create(name:  "Adaptability")
Skill.create(name:  "Teamwork")
Skill.create(name:  "Creativity")
Skill.create(name:  "Flexible")
Skill.create(name:  "Responsible")
Skill.create(name:  "Efficient")
Skill.create(name:  "Detail-oriented")
Skill.create(name:  "Wordpress")
Skill.create(name:  "C")
Skill.create(name:  "C++")
Skill.create(name:  "C#")
Skill.create(name:  "MySql")
Skill.create(name:  "Sqlite3")
Skill.create(name:  "PostgreSQL")
Skill.create(name:  "Bootstrap")
Skill.create(name:  "Materialize")
Skill.create(name:  "Uikit")
Skill.create(name:  "CSS and JavaScript Frameworks")
Skill.create(name:  "Responsive Design")
Skill.create(name:  "Testing/Debugging")
Skill.create(name:  "Sketch")
Skill.create(name:  "Command Line")
Skill.create(name:  "Python")
Skill.create(name:  "iOS/Swift")
Skill.create(name:  "AJAX")
Skill.create(name:  "ASP.NET")
Skill.create(name:  "Objective-C")
Skill.create(name:  "Perl")
Skill.create(name:  "XML")
Skill.create(name:  "Research")
Skill.create(name:  "Oracle")
